cescalara/PartonDensity.jl

- src/bernstein_fit.jl
- src/parametrisations/bernstein.jl
Also includes option to add a seperate bspoly_params for d.
> Vector type fix for fit prior

- src/bernstein_fit.jl
forgot to add the boolean condition for filtering the negatives, should be fine now
> let pos_init_u_only have an actual impact

- examples/forward_model.jl
- src/bernstein_forward_model.jl
- src/cross_section.jl
- src/fit.jl
- src/forward_model.jl
- test/test_forward_model.jl
Remove the global variable Lepcharge
> Remove the global variable Lepcharge

- examples/PDFfit.jl
- examples/generatepseudodata.jl
- examples/priors.jl
Added scripts with fit examples:
- script to generate pseudodata
- script to fit the pseudodata
> Added scripts with fit examples

- .github/workflows/Docs.yml
- .github/workflows/Tests.yml
Switch to Julia 1.9 
@cescalara
> Switch to Julia 1.9

- .github/workflows/Dockerfile
- .github/workflows/Testsv2.yml
> Better Ci, attempt 2

- examples/generatelhapdf.jl
> Add LHAPDF printing program

- examples/forward_model.jl
Added a missing argument to examples
> Added a missing argument to examples

- examples/PDFfit.jl
- examples/generatelhapdf.jl
Write the QCDNUM parameters to the output of the fit
> Write the QCDNUM parameters to the output of the fit

- .github/workflows/Testsv2.yml
- examples/generatepseudodata.jl
- src/MetaData.jl
Nice constructor for MetaData to scale lumi
> Nice constructor for MetaData to scale lumi

- utils/PDFfit.jl
- utils/generatelhapdf.jl
- utils/priors.jl
Drop plots when those are not needed
> Drop plots when those are not needed

- .github/workflows/Testsv2.yml
More tests: test forward_model and pdf_parametrisation
> More tests

- examples/bat_fit_dirichlet.jl
- examples/bat_fit_dirichlet_syserr.jl
- examples/bat_fit_valence.jl
- src/PDploting.jl
- src/bernstein_fit.jl
- src/fit.jl
- src/forward_model.jl
- test/test_forward_model.jl
- test/test_posterior.jl
- utils/PDFfit.jl
Formatting and explicit usage of ZEUS MD
> Formatting and explicit usage of ZEUS MD

- data/ZEUS_I1787035/ZEUS_I1787035.jl
Add the init_sys to the code of data
> Add the init_sys to the code of data

- utils/PDFfit.jl
- utils/generatepseudodata.jl
> Better utils

- .github/workflows/Testsv2.yml
- utils/PDFfit.jl
- utils/generatelhapdf.jl
- utils/generatepseudodata.jl
>  Improve the LHAPDF script

- utils/generatelhapdf.jl
> Updated LHAPDF script

- utils/PDFfit.jl
- utils/generatelhapdf.jl
> Improve LHAPDF script

- utils/PDFfit.jl
- utils/generatelhapdf.jl
Try to modify the fit script to include multiple datasamples
> WIP: Try to modify the fit script to include multiple datasamples

- data/ZEUS_I1787035/ZEUS_I1787035.jl
Use global variables in init_sys
> Use global variables in init_sys

- .github/workflows/Testsv2.yml
- utils/PDFfit.jl
Cosmetic changes to the fit script
> Cosmetic changes to the fit script

- .github/workflows/Testsv2.yml
- utils/PDFfit.jl
> Use multiple datasets

- data/ZEUS_I1787035/ZEUS_I1787035.jl
- examples/forward_model.jl
- examples/zeus_interface.jl
- src/forward_model.jl
Implement the cross-section scaling
note: the systematic uncertainties are the same.
> Implement the cross-section scaling

- .github/workflows/Dockerfile
- utils/PDFfit.jl
Speedup of the fit script due to the usage of let statements
> Speedup of the fit script due to the usage of let statements
